### ISSUE TITLE
Upgrade to MongoDB 3.0 and latest Mongoose.js?

### ISSUE THREAD

**Issue by kachok** [amida-tech/DRE#504]

**Comment by jsachs** [comment]
http://docs.mongodb.org/v3.0/release-notes/3.0-compatibility/

**Comment by oehokie** [comment]
[Mongoose 4.0 Released Today](https://www.mongodb.com/blog/post/introducing-version-40-mongoose-nodejs-odm)

**Comment by oehokie** [comment]
This should be OBE... by updating all the dependencies in release 1.5 you're able to use mongodb 3.0.1 and mongoose 4.0 without errors

Close?
