### ISSUE TITLE
DeepDiff missing from v1.4

### ISSUE THREAD

**Issue by jsachs** [amida-tech/DRE#508]
This results in checkboxes not appearing for allergy rec (and probably others)

ReferenceError: DeepDiff is not defined
    at compareMatches (entrydetails.js:21)
    at Object.fn (entrydetails.js:54)
    at Scope.$digest (angular.js:12650)
    at Scope.$apply (angular.js:12915)
    at done (angular.js:8450)
    at completeRequest (angular.js:8664)
    at XMLHttpRequest.xhr.onreadystatechange (angular.js:8603)

**Comment by ekavaliM** [comment]
working for me, trying updating bower

**Comment by jsachs** [comment]
`grunt build` in the client dir results in line 185 of client/app/index.html getting deleted. It contains the following code:

 <script src="bower_components/diff/releases/deep-diff-0.3.0.min.js"></script>

This is why the checkboxes are going away.

**Comment by jsachs** [comment]
Looks like I was able to remedy this by moving diff from devDependencies to dependencies in the `.bowerrc`.

It's worth noting that on the allergy reconciliation screen, I'm still seeing the following d3.js error:
`Error: Invalid value for <text> attribute x="NaN"d3.js:601 attrFunction`
