### ISSUE TITLE
measurements chart renders off the page

### ISSUE THREAD

**Issue by jsachs** [amida-tech/DRE#510]
![image](https://cloud.githubusercontent.com/assets/954072/6702457/202ed3aa-cd02-11e4-99df-e43a1434bbd5.png)

It looks like it has to do with a difference in how d3 parameters are set initially in measurements.js at line 309, vs. how they are adjusted at lines 57 and 253. Also, the resize code is duplicated, so I am going to refactor this out into a helper function.

**Comment by jsachs** [comment]
Taking a closer look, it looks like the problem may be that the svg chart always has width=1000. The <g> within the chart will resize dynamically, but the chart does not, and I think in certain cases the chart can set the initial scale of the linechart.

**Comment by jsachs** [comment]
The update chart size branch only happens if offsetWidth > 0.
```
if (d3.select(ele[0]).node().offsetWidth > 0) {
   w = d3.select(ele[0]).node().offsetWidth - margin.left - margin.right;
   h = d3.select(ele[0]).node().offsetHeight - margin.top - margin.bottom;
   svg.attr('width', w + margin.left + margin.right).attr('height', h + margin.top + margin.bottom);
}
```

Is there a way we can make sure this gets called even if there is no offset?

**Comment by oehokie** [comment]
How can I reproduce this? I made the window smaller but the chart scaled properly (or is it fixed?)
