### ISSUE TITLE
Buttons misaligned with narrow window

### ISSUE THREAD

**Issue by oehokie** [amida-tech/DRE#512]
Some of the buttons get out of alignment when you shrink the window (Google Chrome)

![screen shot 2015-03-30 at 7 24 20 pm](https://cloud.githubusercontent.com/assets/978362/6909305/a7ec8f5c-d712-11e4-9035-65fb0487d168.png)

**Comment by jsachs** [comment]
Problem is we've got `min-width` styles on these buttons. I need to figure out a graceful way to stack them or move them around once the min width is reached.
