### ISSUE TITLE
troubleshoot swagger on developers site

### ISSUE THREAD

**Issue by ekavaliM** [amida-tech/DRE#515]
{
level: "error",
domain: "validation",
keyword: "oneOf",
message: "instance failed to match exactly one schema (matched 0 out of 2)",
schema: {
loadingURI: "http://swagger.io/v2/schema.json#",
pointer: "/definitions/responseValue"
},
instance: {
pointer: "/paths/~1storage/get/responses/200"
}
}

**Comment by jsachs** [comment]
Doesn't happen locally, interestingly.

**Comment by ekavaliM** [comment]
useful for validating schema: http://json-schema-validator.herokuapp.com/index.jsp
