### ISSUE TITLE
Bower install angular 

### ISSUE THREAD

**Issue by oehokie** [amida-tech/DRE#543]
I get this error when running `bower install --allow-root` in `/client`
![screen shot 2015-04-21 at 4 03 04 pm](https://cloud.githubusercontent.com/assets/978362/7261463/f0251508-e83f-11e4-8ba7-6a5159f11057.png)

**Comment by jsachs** [comment]
I guess we might be using the wrong versions of angular-strap, angular-motion, and angular-animate, but I'm not seeing this issue when I run the command on my machine.
