### ISSUE TITLE
Creating new user and uploading all three files confuses reconciliation interface

### ISSUE THREAD

**Issue by ekavaliM** [amida-tech/DRE#550]
Goes away with refresh.

![image](https://cloud.githubusercontent.com/assets/6115577/7305876/57ebc016-e9cf-11e4-9f06-611c44c6c349.png)

**Comment by jsachs** [comment]
Console errors:
`Can't interpolate: {{formatDate(entryData.observation.date_time.low)}}`
`TypeError: Cannot read property 'precision' of undefined`

It looks like both entryData and and matchData are not in scope.

**Comment by jsachs** [comment]
entryData and matchData are not set in the matches controller, the matches service, or the main dataservice.

At the Allergies record screen entryData is available for each entry, but no matchData is in scope. The time that I just ran through it, it worked. I'm pretty sure that this has to do with there not being a guarantee that entryData/matchData will be set at /matches.

**Comment by jsachs** [comment]
It looks like for matches, entryData and matchData are only set in a $watch on details (entryDetails directive, line 47). My guess is this details watchpoint is getting skipped.

**Comment by oehokie** [comment]
Closed
