### ISSUE TITLE
Meds spacing is off with new icon size

### ISSUE THREAD

**Issue by jsachs** [amida-tech/DRE#559]

**Comment by jsachs** [comment]
![uploads/26e28c87-070c-48e4-9404-65ed19475231/blob](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F26e28c87-070c-48e4-9404-65ed19475231%2Fblob)

**Comment by jsachs** [comment]
Also this:

![image](https://cloud.githubusercontent.com/assets/954072/7401837/d39a2858-ee8c-11e4-9825-46665928a90e.png)

**Comment by ekavaliM** [comment]
first screenshot issue fixed in r-1.5 branch.

**Comment by jsachs** [comment]
Second screen issue also needs to get the real image.

**Comment by jsachs** [comment]
closed by #647
