### ISSUE TITLE
add patient entered flag into data model

### ISSUE THREAD

**Issue by kachok** [amida-tech/DRE#598]

**Comment by kachok** [comment]
jacob:
planning on having it be `patient_entered: boolean`
at same level as `is_brand` and `sig` and the like

dmitry:
I need to add it into every entry
was thinking create like “metadata” field for every entry where it will be folded

**Comment by jsachs** [comment]
Check out my initial branch on bb-record for how it's happening on the backend. We can easily switch the entries to `meta` elements.
