### ISSUE TITLE
No record view 

### ISSUE THREAD

**Issue by ekavaliM** [amida-tech/DRE#658]
When no record is uploaded, measurements chart and entry timelines are still trying to show 

![screen shot 2015-05-18 at 2 34 04 pm](https://cloud.githubusercontent.com/assets/6115577/7687413/2c81d686-fd6b-11e4-8b57-c1bf6ef0d763.png)
![screen shot 2015-05-18 at 2 34 18 pm](https://cloud.githubusercontent.com/assets/6115577/7687424/36b2adf6-fd6b-11e4-887d-d52937172b49.png)

**Comment by oehokie** [comment]
This should be closed

**Comment by ekavaliM** [comment]
yup looks good in my branch
