### ISSUE TITLE
Header Reconcile link not working

### ISSUE THREAD

**Issue by oehokie** [amida-tech/DRE#662]
As a result of #661 review header link does not work, but entry "pending update" link does

![screen shot 2015-05-20 at 11 37 32 am](https://cloud.githubusercontent.com/assets/978362/7729826/d9eecb88-fee4-11e4-9232-a01f662470a7.png)

**Comment by ekavaliM** [comment]
header link hasn't ever worked, do we want to add that functionality?

**Comment by oehokie** [comment]
I'm referring to the "4 updates to your immunizations requiring review" link... that's never worked?

**Comment by ekavaliM** [comment]
yup

**Comment by kachok** [comment]
remove <a>

**Comment by oehokie** [comment]
Link removed, only displays text now
