### ISSUE TITLE
Print my record is broken

### ISSUE THREAD

**Issue by kachok** [amida-tech/DRE#663]
needs review

**Comment by oehokie** [comment]
Print works for me... @jsachs ?

**Comment by jsachs** [comment]
I'll take a look. Is this in release-1.5?

**Comment by oehokie** [comment]
try 1.5 first, but @ekavaliM saw it in my PR #661

**Comment by jsachs** [comment]
Works for me too. Gonna close. @kachok Did you make sure to run all of the build stuff?

**Comment by kachok** [comment]
nope, just pulled issue from slack/comments, so it is not lost
didn't run since readme was outdated : )
