### ISSUE TITLE
medications need refresh after adding

### ISSUE THREAD

**Issue by ekavaliM** [amida-tech/DRE#684]
new patient-entered medications saved but don't show up in medication list right after entering

**Comment by oehokie** [comment]
add dataservice to the medication entry controller, and on successful add call:  `dataservice.forceRefresh();`

**Comment by jsachs** [comment]
When did you take out `$route.reload()`? I had this in the save medication function before in the record controller. Was there a reason it wasn't working any more?

**Comment by jsachs** [comment]
Oh, looks like it's actually still in the meds modal, but it's called from the modal scope, not the record scope.

**Comment by oehokie** [comment]
using `$route.reload` AND `$location.path` was causing the weird double screen issue

**Comment by jsachs** [comment]
Oh interesting. Okay, I'll make the dataservice change.

**Comment by jsachs** [comment]
@oehokie did you mean add it to the modal controller or the record controller?
