### ISSUE TITLE
 js errors (from timeline/measurements) after file upload

### ISSUE THREAD

**Issue by oehokie** [amida-tech/DRE#701]
timeline/measurements is probably getting called before the data is available

**Comment by kachok** [comment]
still there:
upload bb-01
get:
Error: Invalid value for <text> attribute x="NaN"attrFunction @ d3.js:672
d3.js:672 Error: Invalid value for <rect> attribute x="NaN"attrFunction @ d3.js:672
d3.js:672 Error: Invalid value for <rect> attribute width="NaN"attrFunction @ d3.js:672
2d3.js:672 Error: Invalid value for <circle> attribute cx="NaN"

**Comment by oehokie** [comment]
Steps to reproduce?

**Comment by kachok** [comment]
seems to be cached version of frontend/scripts. can't reproduce on latest 1.5 branch
