### ISSUE TITLE
registration year bug

### ISSUE THREAD

**Issue by oehokie** [amida-tech/DRE#714]
When I register for debugging I use 01-01-0001 as the birthdate and it displays 0001, but registers as 1901. (i do 1 tab 1 tab 1).

I think the backend action or registering as 1901 is probably appropriate, but it should display that.

If you enter 2001 it registers as 2001, no problem

**Comment by kachok** [comment]
I would ignore, but it shouldn't allow dates before 1900 since they are probably invalid.
