### ISSUE TITLE
export CCDA not working

### ISSUE THREAD

**Issue by ekavaliM** [amida-tech/DRE#725]
Exporting MHR after uploading bb-01, bb-updated-02, bb-cms-03 files exports the following xml file: 
![screen shot 2015-05-26 at 1 12 34 pm](https://cloud.githubusercontent.com/assets/6115577/7818310/074e40d6-03a9-11e5-9258-7d56c674fa31.png)

**Comment by oehokie** [comment]
Curious, because /api/v1/master_health_record/json works fine...

**Comment by oehokie** [comment]
Appears to be a blue-button-generate issue

**Comment by oehokie** [comment]
@kachok looks like in blue-button-generate/lib/engine.js something happened to existsWhen in "template".  (Line 76... `var condition = template.existsWhen;`)  condition ends up being undefined (though it still goes inside of the if statement below)
