### ISSUE TITLE
FDA data set integration.

### ISSUE THREAD

**Issue by mmccall** [amida-tech/DRE#96]
From Henry- anyone figured out how to do a simple web app that sucks in a Blue Button file and checks against this new FDA data that openFDA API pumps out? Eg if you are taking a drug, and had an adverse event say a rash or nausea  how many other patients have reported the same thing, and, how can you report it to the FDA if you'd like?

OpenFDA API -  launching the openFDA on Monday, June 2nd at the Health Datapalooza. As part of that release, FDA will be releasing millions of adverse event and medication error reports online via our new API. Previously this data was only available via FOIA requests or in a quarterly report that was almost impossible to use. This is the first of many data releases we have planned – in July we’ll be releasing FDA’s product recall dataset and in August FDA’s product labels dataset.

**Comment by kachok** [comment]
added in backlog on Asana
